package com.prystupa

import collection.mutable.ListBuffer


/**
 * Represents matching result generated by
 * By matching engine
 *
 * Order chain - orders that resulted in a match
 * notional chain - represents chain of notional on which match occured
 * Date: 10/7/12
 * Time: 5:07 PM
 */
class MatchingChain(val matchingUnits: List[MatchingUnit], val matchNotional: Int) {


  /**
   * Represents matching result chain
   * @param matchingUnit appends matching unit
   * @return
   */
  def append(matchingUnit: MatchingUnit): MatchingChain = {
    val newNotional = matchingUnit.notional
    val newMatchingUnits = matchingUnit :: matchingUnits
    new MatchingChain(newMatchingUnits, newNotional)
  }
}
